- name: Create Executable
        run: pyinstaller --onefile --windowed compound_interest.py

      - name: Upload Finished File
        uses: actions/upload-artifact@v4
        with:
          name: mac-interest-calculator
          # This grabs BOTH the app and the helper script
          path: |
            dist/compound_interest
            run.command
